<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType><TargetFramework>net8.0-windows</TargetFramework><UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>MchoseBattery</AssemblyName><Version>1.0.1</Version><Description>MCHOSE A7 Pro 電量系統匣</Description>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../MchoseBattery.Core/MchoseBattery.Core.csproj" /><PackageReference Include="HidSharp" Version="2.6.4" /></ItemGroup>
</Project>
